import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useBearStore } from '@store/useStore';
import Code from '@components/Code';

export default function Bear() {

  const bears = useBearStore((state) => state.bears);
  const increaseBear = useBearStore((state) => state.increasePopulation);
  const decreaseBear = useBearStore((state) => state.decreasePopulation);
  const removeBears = useBearStore((state) => state.removeAllBears);

  return (
    <>
      <Head>
        <title>Bear Data 🐻</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Bear Data 🐻</h1>

          <div className="my-8">
            <p className="dark:text-white my-2">{bears} bears around here </p>
            <button onClick={increaseBear} className="bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">one up</button>
            <button onClick={decreaseBear} className="bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">one down</button>
            <button onClick={removeBears} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';

export const useBearStore = create((set) => ({
  bears: 1,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  decreasePopulation: () => set((state) => ({ bears: state.bears - 1 })),
  removeAllBears: () => set({ bears: 0 }),
}))`} />

          <Code name="pages/bear" code={`import { useBearStore } from '@store/useStore';

export default function Bear() {

  const bears = useBearStore((state) => state.bears);
  const increaseBear = useBearStore((state) => state.increasePopulation);
  const decreaseBear = useBearStore((state) => state.decreasePopulation);
  const removeBears = useBearStore((state) => state.removeAllBears);
  
  return (
    <p>{bears} bears around here </p>
    <button onClick={increaseBear}>one up</button>
    <button onClick={decreaseBear}>one down</button>
    <button onClick={removeBears}>remove</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
