import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useCountStore } from '@store/useStore';
import Code from '@components/Code';

export default function Count() {

  const count = useCountStore((state) => state.count);
  const incrementCount = useCountStore((state) => state.increment);
  const incrementByAmount = useCountStore((state) => state.incrementByAmount);
  const decrementCount = useCountStore((state) => state.decrement);
  const decrementByAmount = useCountStore((state) => state.decrementByAmount);
  const resetCount = useCountStore((state) => state.reset);

  return (
    <>
      <Head>
        <title>Count Data 🎰</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Count Data 🎰</h1>

          <div className="my-8 dark:text-white">
            <p className="dark:text-white my-2">{count} count</p>
            <button onClick={incrementCount} className="bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">increment 1</button>
            <button onClick={() => incrementByAmount(5)} className="bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">increment 5</button>
            <button onClick={decrementCount} className="bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">decrement 1</button>
            <button onClick={() => decrementByAmount(5)} className="bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">decrement 5</button>
            <button onClick={resetCount} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">reset</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';

export const useCountStore = create((set) => ({
  count: 0,
  increment: () => set((state) => ({ count: state.count + 1 })),
  incrementByAmount: (amount) =>
    set((state) => ({ count: state.count + amount })),
  decrement: () => set((state) => ({ count: state.count - 1 })),
  decrementByAmount: (amount) =>
    set((state) => ({ count: state.count - amount })),
  reset: () => set({ count: 0 }),
}));`} />

          <Code name="pages/count" code={`import { useCountStore } from '@store/useStore';

export default function Count() {

  const count = useCountStore((state) => state.count);
  const incrementCount = useCountStore((state) => state.increment);
  const incrementByAmount = useCountStore((state) => state.incrementByAmount);
  const decrementCount = useCountStore((state) => state.decrement);
  const decrementByAmount = useCountStore((state) => state.decrementByAmount);
  const resetCount = useCountStore((state) => state.reset);
  
  return (
    <p>{count} count</p>
    <button onClick={incrementCount}>increment 1</button>
    <button onClick={() => incrementByAmount(5)}>increment 5</button>
    <button onClick={decrementCount}>decrement 1</button>
    <button onClick={() => decrementByAmount(5)}>decrement 5</button>
    <button onClick={resetCount}>reset</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
