import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useLionStore } from '@store/useStore';
import Code from '@components/Code';

export default function Lion() {

  const lions = useLionStore((state) => state.lion);
  const increaseLion = useLionStore((state) => state.increasePopulation);
  const decreaseLion = useLionStore((state) => state.decreasePopulation);
  const removeLions = useLionStore((state) => state.removeAllLions);

  return (
    <>
      <Head>
        <title>Lion Data 🦁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Lion Data 🦁</h1>

          <div className="my-8">
            <p className="dark:text-white my-2">{lions} lions around here</p>
            <button onClick={increaseLion} disabled={lions === 5} className={`${lions === 5 && 'cursor-not-allowed'} bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>one up</button>
            <button onClick={decreaseLion} disabled={lions === 0} className={`${lions === 0 && 'cursor-not-allowed'} bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>one down</button>
            <button onClick={removeLions} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';

export const useLionStore = create((set) => ({
  lion: 2,
  increasePopulation: () => set((state) => ({ lion: state.lion + 1 })),
  decreasePopulation: () => set((state) => ({ lion: state.lion - 1 })),
  removeAllLions: () => set({ lion: 0 }),
}))`} />

          <Code name="pages/lion" code={`import { useLionStore } from '@store/useStore';

export default function Lion() {

  const lions = useLionStore((state) => state.lion);
  const increaseLion = useLionStore((state) => state.increasePopulation);
  const decreaseLion = useLionStore((state) => state.decreasePopulation);
  const removeLions = useLionStore((state) => state.removeAllLions);

  return (
    <p>{lions} lions around here</p>
    <button onClick={increaseLion} disabled={lions === 5} className={'\${lions === 5 && 'cursor-not-allowed'}'}>one up</button>
    <button onClick={decreaseLion} disabled={lions === 0} className={'\${lions === 0 && 'cursor-not-allowed'}'}>one down</button>
    <button onClick={removeLions}>remove</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
