import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useRef } from 'react';
import { useNameStore } from '@store/useStore';
import Code from '@components/Code';

export default function Name() {

  const inputNameRef = useRef()
  const name = useNameStore(state => state.name)
  const setName = useNameStore(state => state.setName)
  const resetName = useNameStore(state => state.resetName)
  function handleChangeName() {
    const value = inputNameRef.current.value
    if (value !== "") setName(value)
    else alert("name cannot empty !")
    inputNameRef.current.value = ''
  }

  return (
    <>
      <Head>
        <title>Default Zustand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Name Data 😀</h1>

          <div className="my-8 dark:text-white">
            <p className="dark:text-white my-2">Name : {name}</p>
            <div className="mb-2">
              <input ref={inputNameRef} className="px-1.5 mr-2 h-7 border border-gray-300 dark:border-neutral-700 rounded bg-gray-100 dark:bg-neutral-800 dark:text-white focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" />
              <button onClick={handleChangeName} className={`bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>change name</button>
            </div>
            <button onClick={resetName} className={`bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>reset name</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';
          
export const useNameStore = create((set) => ({
  name: 'John Doe',
  setName: (param) => set({ name: param }),
  resetName: () => set({ name: 'John Doe' })
}))`} />

          <Code name="pages/name" code={`import { useRef } from 'react';
import { useNameStore } from '@store/useStore';

export default function Name() {

  const inputNameRef = useRef()
  const name = useNameStore(state => state.name)
  const setName = useNameStore(state => state.setName)
  const resetName = useNameStore(state => state.resetName)
  function handleChangeName() {
    const value = inputNameRef.current.value
    if (value !== "") setName(value)
    else alert("name cannot empty !")
    inputNameRef.current.value = ''
  }

  return (
    <p>Name : {name}</p>
    <div>
      <input ref={inputNameRef} />
      <button onClick={handleChangeName}>change name</button>
    </div>
    <button onClick={resetName}>reset name</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
