import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useSharkStore } from '@store/useStore';
import Code from '@components/Code';

export default function Shark() {

  const sharks = useSharkStore((state) => state.shark);
  const increaseShark = useSharkStore((state) => state.increasePopulation);
  const decreaseShark = useSharkStore((state) => state.decreasePopulation);
  const removeSharks = useSharkStore((state) => state.removeAllSharks);

  return (
    <>
      <Head>
        <title>Shark Data 🦈</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Shark Data 🦈</h1>

          <div className="my-8">
            <p className="dark:text-white my-2">{sharks} sharks around here</p>
            <button onClick={increaseShark} className={`${sharks === 5 && 'cursor-not-allowed'} bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>one up</button>
            <button onClick={decreaseShark} className={`${sharks === 0 && 'cursor-not-allowed'} bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>one down</button>
            <button onClick={removeSharks} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';
          
export const useSharkStore = create((set) => ({
  shark: 3,
  increasePopulation: () => set((state) => ({
    shark: state.shark < 5 ? state.shark + 1 : 5
  })),
  decreasePopulation: () => set((state) => ({
    shark: state.shark > 0 ? state.shark - 1 : 0
  })),
  removeAllSharks: () => set({ shark: 0 }),
}))`} />

          <Code name="pages/shark" code={`import { useSharkStore } from '@store/useStore';

export default function Shark() {

  const sharks = useSharkStore((state) => state.shark);
  const increaseShark = useSharkStore((state) => state.increasePopulation);
  const decreaseShark = useSharkStore((state) => state.decreasePopulation);
  const removeSharks = useSharkStore((state) => state.removeAllSharks);

  return (
    <p>{sharks} sharks around here</p>
    <button onClick={increaseShark} className={'\${sharks === 5 && 'cursor-not-allowed'}'}>one up</button>
    <button onClick={decreaseShark} className={'\${sharks === 0 && 'cursor-not-allowed'}'}>one down</button>
    <button onClick={removeSharks}>remove</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
