import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useRef, useState } from 'react';
import { useStudentStore } from '@store/useStore';
import Code from '@components/Code';

export default function Student() {

  const studentNameRef = useRef()
  const [editedId, setEditedId] = useState()
  const [editedName, setEditedName] = useState()
  const [showEdit, setShowEdit] = useState(false)
  const students = useStudentStore(state => state.students)
  const addStudent = useStudentStore(state => state.addStudent)
  const removeStudent = useStudentStore(state => state.removeStudent)
  const removeAllStudents = useStudentStore(state => state.removeAllStudents)
  const updateStudent = useStudentStore(state => state.updateStudent)
  const restoreAllStudents = useStudentStore(state => state.restoreAllStudents)
  function handleAddStudent() {
    const value = studentNameRef.current.value
    if (value !== "") addStudent(value)
    else alert("student name cannot empty !")
    studentNameRef.current.value = ''
  }
  function handleEditStudent(id, name) {
    setEditedId(id)
    setEditedName(name)
    setShowEdit(true)
  }
  function handleUpdateStudent() {
    if (editedName === "") {
      alert("student name cannot empty !")
    }
    else {
      updateStudent(editedId, editedName)
      setShowEdit(false)
      setEditedId('')
      setEditedName('')
    }
  }
  function handleRemoveStudent(id) {
    removeStudent(id)
  }

  return (
    <>
      <Head>
        <title>Student Data 🧑🏻‍🎓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Student Data 🧑🏻‍🎓</h1>

          <div className="my-8 dark:text-white">
            <ul className="dark:text-white my-2 space-y-2">
              {students.map(student =>
                <li key={student.id}>
                  {student.name}
                  <button onClick={() => handleEditStudent(student.id, student.name)} className={`bg-yellow-500 hover:bg-yellow-600 font-medium transition-all cursor-pointer text-white rounded text-sm ml-2`}>✏️</button>
                  <button onClick={() => handleRemoveStudent(student.id)} className={`bg-red-500 hover:bg-red-600 font-medium transition-all cursor-pointer text-white rounded px-1.5 text-sm ml-2`}>X</button>
                </li>
              )}
            </ul>
            <span className="mt-2 dark:text-white">{students.length} students found</span>
            <p className="dark:text-white my-2">Add a new student</p>
            <div className="mb-2">
              <input ref={studentNameRef} className="px-1.5 mr-2 h-7 border border-gray-300 dark:border-neutral-700 rounded bg-gray-100 dark:bg-neutral-800 dark:text-white focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" />
              <button onClick={handleAddStudent} className={`bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>add student</button>
            </div>
            {showEdit &&
              <>
                <p className="dark:text-white my-2">Edit student</p>
                <div className="mb-4">
                  <input value={editedName} onChange={(e) => setEditedName(e.target.value)} className="px-1.5 mr-2 h-7 border border-gray-300 dark:border-neutral-700 rounded bg-gray-100 dark:bg-neutral-800 dark:text-white focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" />
                  <button onClick={handleUpdateStudent} className={`bg-violet-500 hover:bg-violet-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>Update student</button>
                  <button onClick={() => setShowEdit(false)} className={`bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>Cancel</button>
                </div>
              </>
            }
            <button onClick={removeAllStudents} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove all</button>
            <button onClick={restoreAllStudents} className="bg-teal-500 hover:bg-teal-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">restore all</button>
          </div>

          <Code name="store/useStore" code={`import create from 'zustand';
          
export const useStudentStore = create(set => ({
  students: [
    { id: '1', name: 'Aaron Saunders' },
    { id: '2', name: 'Andrea Saunders' },
    { id: '3', name: 'Bill Smith' },
    { id: '4', name: 'John Chambers' },
    { id: '5', name: 'Joe Johnson' }
  ],
  addStudent: (name) =>
    set(state => ({
      students: [
        ...state.students,
        {
          name: name,
          id: Math.random() * 100 + '',
        }
      ]
    })),
  removeStudent: (id) =>
    set(state => ({
      students: state.students.filter(student => student.id !== id)
    })),
  updateStudent: (id, name) =>
    set(state => ({
      students: state.students.map(item => {
        if (item.id === id) {
          return {
            ...item,
            name: name
          };
        } else {
          return item;
        }
      })
    })),
  removeAllStudents: () => set({ students: [] }),
  restoreAllStudents: () => set({
    students: [
      { id: '1', name: 'Aaron Saunders' },
      { id: '2', name: 'Andrea Saunders' },
      { id: '3', name: 'Bill Smith' },
      { id: '4', name: 'John Chambers' },
      { id: '5', name: 'Joe Johnson' }
    ]
  })
}));`} />

          <Code name="pages/student" code={`import { useRef, useState } from 'react';
import { useStudentStore } from '@store/useStore';

export default function Student() {

  const studentNameRef = useRef()
  const [editedId, setEditedId] = useState()
  const [editedName, setEditedName] = useState()
  const [showEdit, setShowEdit] = useState(false)
  const students = useStudentStore(state => state.students)
  const addStudent = useStudentStore(state => state.addStudent)
  const removeStudent = useStudentStore(state => state.removeStudent)
  const removeAllStudents = useStudentStore(state => state.removeAllStudents)
  const updateStudent = useStudentStore(state => state.updateStudent)
  const restoreAllStudents = useStudentStore(state => state.restoreAllStudents)
  function handleAddStudent() {
    const value = studentNameRef.current.value
    if (value !== "") addStudent(value)
    else alert("student name cannot empty !")
    studentNameRef.current.value = ''
  }
  function handleEditStudent(id, name) {
    setEditedId(id)
    setEditedName(name)
    setShowEdit(true)
  }
  function handleUpdateStudent() {
    if (editedName === "") {
      alert("student name cannot empty !")
    }
    else {
      updateStudent(editedId, editedName)
      setShowEdit(false)
      setEditedId('')
      setEditedName('')
    }
  }
  function handleRemoveStudent(id) {
    removeStudent(id)
  }

  return (
    <ul>
      {students.map(student =>
        <li key={student.id}>
          {student.name}
          <button onClick={() => handleEditStudent(student.id, student.name)}>✏️</button>
          <button onClick={() => handleRemoveStudent(student.id)}>X</button>
        </li>
      )}
    </ul>
    <span>{students.length} students found</span>
    <p>Add a new student</p>
    <div>
      <input ref={studentNameRef} />
      <button onClick={handleAddStudent}>add student</button>
    </div>
    {
      showEdit &&
      <>
        <p>Edit student</p>
        <div>
          <input value={editedName} onChange={(e) => setEditedName(e.target.value)}/>
          <button onClick={handleUpdateStudent}>Update student</button>
          <button onClick={() => setShowEdit(false)}>Cancel</button>
        </div>
      </>
    }
    <button onClick={removeAllStudents}>remove all</button>
    <button onClick={restoreAllStudents}>restore all</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
